name: shopify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  dots_indicator: ^4.0.1
  firebase_ai: ^3.0.0
  firebase_app_check: ^0.4.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_floating_bottom_bar: ^1.3.0
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  flutter_typeahead: ^5.2.0
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  get_it: ^8.0.3
  google_nav_bar: ^5.0.7
  google_sign_in: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  iconsax: ^0.0.8
  iconsax_flutter: ^1.0.1
  image_picker: ^1.1.2
  ionicons: ^0.2.2
  modal_progress_hud_nsn: ^0.5.1
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  persistent_bottom_nav_bar: ^6.2.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/imgs/category_svgs/
    - assets/imgs/svgs/
    - assets/imgs/banners/
    - assets/imgs/my_images/

  fonts:
    - family: Ancizar Sans
      fonts:
        - asset: fonts/Inter-VariableFont_opsz,wght.ttf
