// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq9_3Zz0-Y3wnfWE3LvFyLEJFNCAen8ZU',
    appId: '1:691942275788:web:0150e02da4dfef4517a069',
    messagingSenderId: '691942275788',
    projectId: 'shoply-bb6b6',
    authDomain: 'shoply-bb6b6.firebaseapp.com',
    storageBucket: 'shoply-bb6b6.firebasestorage.app',
    measurementId: 'G-DNJFSE3HYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzuQ9Whh7HkejS2ZfYxccAWUWLVgzgS8E',
    appId: '1:691942275788:android:ea517b9f0ec5317c17a069',
    messagingSenderId: '691942275788',
    projectId: 'shoply-bb6b6',
    storageBucket: 'shoply-bb6b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWJanXhKHDVdcxooWJt7in3u1TzpTB1Ow',
    appId: '1:691942275788:ios:b1802856a3a328e117a069',
    messagingSenderId: '691942275788',
    projectId: 'shoply-bb6b6',
    storageBucket: 'shoply-bb6b6.firebasestorage.app',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWJanXhKHDVdcxooWJt7in3u1TzpTB1Ow',
    appId: '1:691942275788:ios:b1802856a3a328e117a069',
    messagingSenderId: '691942275788',
    projectId: 'shoply-bb6b6',
    storageBucket: 'shoply-bb6b6.firebasestorage.app',
    iosBundleId: 'com.example.shopify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq9_3Zz0-Y3wnfWE3LvFyLEJFNCAen8ZU',
    appId: '1:691942275788:web:f20bc44411aaa13217a069',
    messagingSenderId: '691942275788',
    projectId: 'shoply-bb6b6',
    authDomain: 'shoply-bb6b6.firebaseapp.com',
    storageBucket: 'shoply-bb6b6.firebasestorage.app',
    measurementId: 'G-ZQSPS436YG',
  );

}